package com.github.fontys;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String args[]) {
        for (int i = 0; i < 5; i++) {
            System.out.println(String.format("Print number %s. From jenkins now!", i));
        }
    }
}
