package com.github.fontys;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String args[]) {
        System.out.println("Test print");
        System.out.println("Test print");
        System.out.println("Test print");
        System.out.println("Test print");
        System.out.println("Test print");
        for (int i = 0; i < 100; i++) {
            System.out.println("Testing!!!!");
        }
    }

    /*
    public App(){
        register(MultiPartFeature.class);
        packages("com.github.fontys.beans");
       // register(new LoggingFeature(Logger.getLogger(App.class.getName()), LoggingFeature.Verbosity.PAYLOAD_ANY));
    }*/

    /*
    @Override
    public Set<Class<?>> getClasses() {
        final Set<Class<?>> classes = new HashSet<Class<?>>();
        // register resources and features
        classes.add(MultiPartFeature.class);
        return classes;
    }*/

}
