package com.github.fontys;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String args[]) {
        for (int i = 0; i < 5; i++) {
        //    System.out.println("This was run from the main(String args[]) method inside App.java!");
            System.out.println("Just a print!");
        }
    }

    /*
    public App(){
        register(MultiPartFeature.class);
        packages("com.github.fontys.beans");
       // register(new LoggingFeature(Logger.getLogger(App.class.getName()), LoggingFeature.Verbosity.PAYLOAD_ANY));
    }*/

    /*
    @Override
    public Set<Class<?>> getClasses() {
        final Set<Class<?>> classes = new HashSet<Class<?>>();
        // register resources and features
        classes.add(MultiPartFeature.class);
        return classes;
    }*/

}
